<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.tl</groupId>
  <artifactId>tl-live-app</artifactId>
  <version>1.0</version>
  <packaging>pom</packaging>

  <name>tl-live-app</name>
  <url>http://maven.apache.org</url>
  <modules>
    <module>tl-live-api</module>
    <module>tl-live-user</module>
      <module>tl-live-common</module>
      <module>tl-live-redis-starter</module>
      <module>tl-live-id-generate</module>
    <module>tl-live-id-generate</module>
      <module>tl-live-gateway</module>
    <module>tl-live-gateway</module>
      <module>tl-live-im</module>
  </modules>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <dubbo.version>3.2.9</dubbo.version>
    <spring-cloud-bootstrap.version>3.0.2</spring-cloud-bootstrap.version>
    <mysql.version>8.0.28</mysql.version>
    <mybatis-plus.version>3.5.3</mybatis-plus.version>
    <cosid.version>2.6.8</cosid.version>
    <java-sms-sdk>1.0.4</java-sms-sdk>
    <spring-cloud-starter-gateway.version>4.0.6</spring-cloud-starter-gateway.version>
    <fastjson.version>2.0.42</fastjson.version>
    <spring-cloud-starter-loadbalancer.version>4.0.3</spring-cloud-starter-loadbalancer.version>
    <rocketmq.springboot.version>2.3.0</rocketmq.springboot.version>
    <rocketmq.version>5.2.0</rocketmq.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>3.0.4</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-alibaba-dependencies</artifactId>
        <version>2022.0.0.0-RC2</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.13.2</version>
        <scope>test</scope>
      </dependency>



    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>17</source>
          <target>17</target>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
