server:
  port: 80

spring:
  application:
    name: tl-live-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: tl-live
    gateway:
      discovery:
        locator:
            enabled: true
      routes:
        - id: tl-live-user
          uri: lb://tl-live-api
          predicates:
            - Path=/user/**,/sms/**,/im/**
tltk:
  gateway:
    whitelist:
      - /sms/loginPhone
      - /sms/sendLoginSms
      - /im/getIMServer
      - /im/sendRoomNotice


dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848?namespace=tl-live
    id: nacos-registry
  protocol:
    name: dubbo
    port: -1