<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.tl</groupId>
    <artifactId>tl-live-app</artifactId>
    <version>1.0</version>
  </parent>

  <artifactId>tl-live-api</artifactId>
  <packaging>jar</packaging>

  <name>tl-live-api</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo-spring-boot-starter</artifactId>
      <version>${dubbo.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-bootstrap</artifactId>
      <version>${spring-cloud-bootstrap.version}</version>
    </dependency>
    <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    </dependency>
    <dependency>
      <groupId>org.tl</groupId>
      <artifactId>tl-live-user-interface</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>org.tl</groupId>
      <artifactId>tl-live-user-interface</artifactId>
      <version>1.0</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.tl.live</groupId>
      <artifactId>tl-live-id-generate-provider</artifactId>
      <version>${version}</version>
    </dependency>

    <dependency>
      <groupId>org.tl</groupId>
      <artifactId>tl-live-app</artifactId>
      <version>${version}</version>
    </dependency>

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.12</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.tl.live</groupId>
      <artifactId>tl-live-redis-starter</artifactId>
      <version>1.0</version>
    </dependency>

    <dependency>
      <groupId>org.tl.live</groupId>
      <artifactId>tl-live-redis-starter</artifactId>
      <version>1.0</version>
    </dependency>

    <dependency>
      <groupId>org.tl.live</groupId>
      <artifactId>tl-live-im-interface</artifactId>
      <version>1.0</version>
    </dependency>


  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>3.0.4</version>
        <configuration>
          <classifier>exec</classifier>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
