server:
    port: 8081

#nacos配置
spring:
  application:
    name: tl-live-api
  cloud:
    nacos:
      discovery:
        namespace: tl-live
        server-addr: 127.0.0.1:8848
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10

#dubbo配置
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848?namespace=tl-live
    id: nacos-registry
  protocol:
    name: dubbo
    port: -1

tllive:
  im:
    imInstance: tl-live-im-server




